defaults:
  - task_tuning
  - model_config: vae
  - training_loop_config/optimizer_config: optim_adam
  - training_loop_config/lr_scheduler_config: null

batch_size: 10

model_config:
  num_hidden:
    - 1000
  num_latent: 150
  kl_weight: 0.0001
  dropout_rate: 0.1

training_loop_config:
  max_epochs: 40
  annealing_epochs: 20

  optimizer_config:
    lr: 1e-4
    weight_decay: 0
