
defaults:
  - identify_associations_bayes

batch_size: 10

num_refits: 40

perturbation_config:
  target_dataset_name: random.small.drugs
  target_value: 1

model_config:
  num_hidden:
    - 1000

training_loop_config:
  max_epochs: 40
