
defaults:
  - identify_associations_ttest

batch_size: 10  # number of samples per batch in training loop

num_refits: 10  # number of times to refit (retrain) model

perturbation_config:
  target_dataset_name: random.small.drugs # dataset to perturb
  target_value: 1                         # value to change to

model_config:        # model configuration
  num_hidden:        # list of units in each hidden layer of the VAE encoder/decoder
    - 1000

training_loop_config: # training loop configuration
  max_epochs: 40      # number of epochs
